package com.github.se.project.model.profile

/** Enum classes representing the subject of a user. */
enum class Subject {
  ANALYSIS,
  ALGEBRA,
  PHYSICS,
  ICC,
  AICC,
  COMPUTER_SCIENCE,
  BIOLOGY,
  CHEMISTRY,
  ELECTRICAL_ENGINEERING,
  MECHANICAL_ENGINEERING,
  ARCHITECTURE,
  CIVIL_ENGINEERING,
  ENVIRONMENTAL_SCIENCE,
  MATERIAL_SCIENCE,
  MATHEMATICS,
  MICROTECHNOLOGY,
  NEUROSCIENCE,
  ROBOTICS,
  MANAGEMENT,
  COMMUNICATION,
  NONE
}
